spring.datasource.url=jdbc:postgresql://localhost:5432/acme_salary_db
spring.datasource.username=acme_user
spring.datasource.password=acme_password

# Hibernate batching for seed profile
spring.jpa.properties.hibernate.jdbc.batch_size=500
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.jdbc.batch_versioned_data=true
